[tool.poetry]
name = "streamlit-flask-api"
version = "1.0.0"
description = ""
authors = ["James Neale <42097394+james9226@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = ">=3.8"
Flask = "^2.2.3"
python-dotenv = "^1.0.0"
python-jose = "^3.3.0"
Flask-Cors = "^3.0.10"
six = "^1.16.0"
